### ISSUE TITLE
Medication data input error

### ISSUE THREAD

**Issue by icynow** [JKesslerPhD/FIPInjectionLogger#21]
When I try in input 7/18 it says date exists and skips that day, then on main page says you are NOT up to date

**Comment by JKesslerPhD** [comment]
This issue appeared because I changed how the system handles local timezones.  It looked like you entered data for 7/18 using the old timezone system.  As such, it displayed for you as being entered in 7/17, even though the system showed it as being entered on 7/18 but in a different time zone.  I've fixed the timestamp on that to be consistent with your time zone.

The system says it is not up to date, as it's looking at your most current injection relative to today's date.  If an entry has been made at the most current date, it says it is up to date.  I'll fix the language around this, and change how the system calculates injection logging completeness.

**Comment by JKesslerPhD** [comment]
@icynow If you have noticed anything else wrong with the site, or functionality that would make things easier for you, please let me know.  Shoot me a message on facebook, and I'd be happy to improve the site based on your suggestions.
