### ISSUE TITLE
Saying date already has treatment logged

### ISSUE THREAD

**Issue by lizzyd1991** [JKesslerPhD/FIPInjectionLogger#36]
Trying to log my cat's treatment medication tonight but it's saying that I've already logged a treatment for today.

**Comment by JKesslerPhD** [comment]
This is really tricky. I tried to fix a previous error by having the site better account for timezones, which it wasn't doing a good job on before.  It looks like because the old dates were not timezone aware, and the new one is, it's creating a slight error in reporting

If you click the "Allow multiple entries per day" option, this will allow you to enter the injection for today.

**Comment by JKesslerPhD** [comment]
I believe I have fixed this specific issue.  Because I added timezones aware features to dates being logged starting oct 25th, anything logged before that is going to display incorrect time stamps on the log.  I am working on something to fix this in the next few days.

Sorry about the inconvenience!

**Comment by JKesslerPhD** [comment]
@lizzyd1991 I believe all errors on the site are fixed.  The site now asks you to define your specific timezone, and all times are recorded and displayed relative to what you enter.  Please let me know if you find any additional errors, but I believe your concerns have been resolved.
